name: Deploy Vue
on: 
  push:
    branches: ["main"]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Vue
    steps:
    - uses: actions/checkout@v3
    - id: deploy
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'banx9x'
        reponame: 'vue-example'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
